export type QuestionFact = {
  id: string;
  topic: string;
  subject: string;
  fact: string;
  correct: string;
  distractors: string[];
  category:
    | "deities"
    | "concepts"
    | "epics"
    | "symbols"
    | "places"
    | "festivals"
    | "texts";
};

export const QUESTION_BANK: QuestionFact[] = [
  {
    id: "deity-yama",
    topic: "Deities",
    subject: "Yama",
    fact: "Yama is traditionally associated with death and judgment.",
    correct: "Yama",
    distractors: ["Brahma", "Vishnu", "Agni"],
    category: "deities",
  },
  {
    id: "deity-brahma",
    topic: "Deities",
    subject: "Brahma",
    fact: "Brahma is traditionally associated with creation in the Trimurti.",
    correct: "Brahma",
    distractors: ["Vishnu", "Shiva", "Indra"],
    category: "deities",
  },
  {
    id: "deity-vishnu",
    topic: "Deities",
    subject: "Vishnu",
    fact: "Vishnu is traditionally associated with preservation in the Trimurti.",
    correct: "Vishnu",
    distractors: ["Brahma", "Shiva", "Yama"],
    category: "deities",
  },
  {
    id: "deity-shiva",
    topic: "Deities",
    subject: "Shiva",
    fact: "Shiva is traditionally associated with destruction and transformation in the Trimurti.",
    correct: "Shiva",
    distractors: ["Brahma", "Vishnu", "Indra"],
    category: "deities",
  },
  {
    id: "deity-indra",
    topic: "Deities",
    subject: "Indra",
    fact: "Indra is traditionally associated with kingship of the devas and with storms and rain in Vedic and later traditions.",
    correct: "Indra",
    distractors: ["Yama", "Brahma", "Agni"],
    category: "deities",
  },
  {
    id: "deity-agni",
    topic: "Deities",
    subject: "Agni",
    fact: "Agni is the Vedic deity associated with fire and sacrificial rites.",
    correct: "Agni",
    distractors: ["Surya", "Yama", "Varuna"],
    category: "deities",
  },
  {
    id: "deity-surya",
    topic: "Deities",
    subject: "Surya",
    fact: "Surya is traditionally associated with the Sun.",
    correct: "Surya",
    distractors: ["Agni", "Vayu", "Soma"],
    category: "deities",
  },
  {
    id: "deity-vayu",
    topic: "Deities",
    subject: "Vayu",
    fact: "Vayu is traditionally associated with wind and air.",
    correct: "Vayu",
    distractors: ["Agni", "Surya", "Varuna"],
    category: "deities",
  },
  {
    id: "deity-varuna",
    topic: "Deities",
    subject: "Varuna",
    fact: "Varuna is an important Vedic deity associated with cosmic order and waters.",
    correct: "Varuna",
    distractors: ["Agni", "Indra", "Surya"],
    category: "deities",
  },
  {
    id: "deity-saraswati",
    topic: "Deities",
    subject: "Saraswati",
    fact: "Saraswati is widely associated with learning, knowledge, music and speech.",
    correct: "Saraswati",
    distractors: ["Lakshmi", "Parvati", "Durga"],
    category: "deities",
  },
  {
    id: "deity-lakshmi",
    topic: "Deities",
    subject: "Lakshmi",
    fact: "Lakshmi is widely associated with prosperity, fortune and abundance.",
    correct: "Lakshmi",
    distractors: ["Saraswati", "Parvati", "Ganga"],
    category: "deities",
  },
  {
    id: "deity-parvati",
    topic: "Deities",
    subject: "Parvati",
    fact: "Parvati is a major goddess traditionally associated with Shiva as his consort.",
    correct: "Parvati",
    distractors: ["Lakshmi", "Saraswati", "Ganga"],
    category: "deities",
  },
  {
    id: "deity-ganesha",
    topic: "Deities",
    subject: "Ganesha",
    fact: "Ganesha is widely worshipped as the remover of obstacles and is associated with beginnings and intellect.",
    correct: "Ganesha",
    distractors: ["Kartikeya", "Surya", "Indra"],
    category: "deities",
  },
  {
    id: "deity-kartikeya",
    topic: "Deities",
    subject: "Kartikeya",
    fact: "Kartikeya is traditionally associated with warfare and is known by several names including Skanda and Murugan.",
    correct: "Kartikeya",
    distractors: ["Ganesha", "Varuna", "Agni"],
    category: "deities",
  },
  {
    id: "deity-hanuman",
    topic: "Deities",
    subject: "Hanuman",
    fact: "Hanuman is a central devotee of Rama in the Ramayana tradition.",
    correct: "Hanuman",
    distractors: ["Arjuna", "Bhima", "Nakula"],
    category: "deities",
  },
  {
    id: "deity-rama",
    topic: "Deities",
    subject: "Rama",
    fact: "Rama is the central royal hero of the Ramayana and is revered as an avatar of Vishnu in many traditions.",
    correct: "Rama",
    distractors: ["Krishna", "Arjuna", "Yudhishthira"],
    category: "deities",
  },
  {
    id: "deity-krishna",
    topic: "Deities",
    subject: "Krishna",
    fact: "Krishna is a major figure in the Mahabharata and is revered as an avatar of Vishnu in many traditions.",
    correct: "Krishna",
    distractors: ["Rama", "Arjuna", "Bhima"],
    category: "deities",
  },
  {
    id: "deity-ganga",
    topic: "Deities",
    subject: "Ganga",
    fact: "Ganga is personified as the sacred river goddess associated with the Ganges River.",
    correct: "Ganga",
    distractors: ["Yamuna", "Saraswati", "Narmada"],
    category: "deities",
  },
  {
    id: "concept-dharma",
    topic: "Concepts",
    subject: "Dharma",
    fact: "Dharma can broadly refer to duty, conduct, moral order or a way of living appropriate to one's context.",
    correct: "Dharma",
    distractors: ["Moksha", "Karma", "Artha"],
    category: "concepts",
  },
  {
    id: "concept-karma",
    topic: "Concepts",
    subject: "Karma",
    fact: "Karma broadly refers to action and its consequences in Indian philosophical traditions.",
    correct: "Karma",
    distractors: ["Dharma", "Moksha", "Artha"],
    category: "concepts",
  },
  {
    id: "concept-moksha",
    topic: "Concepts",
    subject: "Moksha",
    fact: "Moksha broadly refers to liberation from the cycle of rebirth in several Hindu philosophical traditions.",
    correct: "Moksha",
    distractors: ["Karma", "Dharma", "Artha"],
    category: "concepts",
  },
  {
    id: "concept-samsara",
    topic: "Concepts",
    subject: "Samsara",
    fact: "Samsara refers to the cycle of birth, death and rebirth.",
    correct: "Samsara",
    distractors: ["Moksha", "Dharma", "Svarga"],
    category: "concepts",
  },
  {
    id: "concept-ahimsa",
    topic: "Concepts",
    subject: "Ahimsa",
    fact: "Ahimsa is commonly understood as non-violence or non-harming.",
    correct: "Ahimsa",
    distractors: ["Dharma", "Karma", "Moksha"],
    category: "concepts",
  },
  {
    id: "concept-yoga",
    topic: "Concepts",
    subject: "Yoga",
    fact: "Yoga has a wide range of meanings and can refer to spiritual discipline, practice and paths described in Indian traditions.",
    correct: "Yoga",
    distractors: ["Karma", "Dharma", "Naraka"],
    category: "concepts",
  },
  {
    id: "concept-svarga",
    topic: "Concepts",
    subject: "Svarga",
    fact: "Svarga is commonly described as a heavenly realm in Hindu texts and traditions.",
    correct: "Svarga",
    distractors: ["Naraka", "Samsara", "Moksha"],
    category: "concepts",
  },
  {
    id: "concept-naraka",
    topic: "Concepts",
    subject: "Naraka",
    fact: "Naraka is commonly described in Hindu traditions as a realm associated with punishment.",
    correct: "Naraka",
    distractors: ["Svarga", "Moksha", "Vaikuntha"],
    category: "concepts",
  },
  {
    id: "place-kailasa",
    topic: "Places",
    subject: "Mount Kailasa",
    fact: "Mount Kailasa is traditionally associated with Shiva.",
    correct: "Mount Kailasa",
    distractors: ["Mount Meru", "Ayodhya", "Dwarka"],
    category: "places",
  },
  {
    id: "place-ayodhya",
    topic: "Places",
    subject: "Ayodhya",
    fact: "Ayodhya is traditionally associated with Rama and is a major sacred city in Hindu tradition.",
    correct: "Ayodhya",
    distractors: ["Mathura", "Dwarka", "Kashi"],
    category: "places",
  },
  {
    id: "place-mathura",
    topic: "Places",
    subject: "Mathura",
    fact: "Mathura is traditionally associated with Krishna's birth and early life.",
    correct: "Mathura",
    distractors: ["Ayodhya", "Dwarka", "Kashi"],
    category: "places",
  },
  {
    id: "place-dwarka",
    topic: "Places",
    subject: "Dwarka",
    fact: "Dwarka is traditionally associated with Krishna.",
    correct: "Dwarka",
    distractors: ["Ayodhya", "Mathura", "Kashi"],
    category: "places",
  },
  {
    id: "place-kashi",
    topic: "Places",
    subject: "Kashi",
    fact: "Kashi, also called Varanasi, is one of the most important sacred cities in Hindu tradition and is strongly associated with Shiva.",
    correct: "Kashi",
    distractors: ["Ayodhya", "Mathura", "Ujjain"],
    category: "places",
  },
  {
    id: "text-rigveda",
    topic: "Texts",
    subject: "Rigveda",
    fact: "The Rigveda is one of the four Vedas and contains hymns in Vedic Sanskrit.",
    correct: "Rigveda",
    distractors: ["Ramayana", "Mahabharata", "Puranas"],
    category: "texts",
  },
  {
    id: "text-yajurveda",
    topic: "Texts",
    subject: "Yajurveda",
    fact: "The Yajurveda is one of the four Vedas and is closely connected with formulas and procedures for ritual sacrifice.",
    correct: "Yajurveda",
    distractors: ["Samaveda", "Atharvaveda", "Ramayana"],
    category: "texts",
  },
  {
    id: "text-samaveda",
    topic: "Texts",
    subject: "Samaveda",
    fact: "The Samaveda is one of the four Vedas and is particularly associated with chants and melodies used in ritual.",
    correct: "Samaveda",
    distractors: ["Rigveda", "Atharvaveda", "Mahabharata"],
    category: "texts",
  },
  {
    id: "text-atharvaveda",
    topic: "Texts",
    subject: "Atharvaveda",
    fact: "The Atharvaveda is one of the four Vedas and includes hymns, spells and material concerning everyday life and ritual.",
    correct: "Atharvaveda",
    distractors: ["Yajurveda", "Ramayana", "Bhagavata Purana"],
    category: "texts",
  },
  {
    id: "text-ramayana",
    topic: "Texts",
    subject: "Ramayana",
    fact: "The Ramayana centers on Rama, Sita, Lakshmana and the journey to Lanka.",
    correct: "Ramayana",
    distractors: ["Mahabharata", "Rigveda", "Upanishads"],
    category: "epics",
  },
  {
    id: "text-mahabharata",
    topic: "Texts",
    subject: "Mahabharata",
    fact: "The Mahabharata includes the conflict between the Pandavas and Kauravas and contains the Bhagavad Gita.",
    correct: "Mahabharata",
    distractors: ["Ramayana", "Rigveda", "Manusmriti"],
    category: "epics",
  },
  {
    id: "text-gita",
    topic: "Texts",
    subject: "Bhagavad Gita",
    fact: "The Bhagavad Gita is a dialogue between Krishna and Arjuna on the battlefield of Kurukshetra.",
    correct: "Bhagavad Gita",
    distractors: ["Ramayana", "Arthashastra", "Rigveda"],
    category: "texts",
  },
  {
    id: "text-upanishads",
    topic: "Texts",
    subject: "Upanishads",
    fact: "The Upanishads are philosophical texts concerned with topics such as Brahman, Atman and liberation.",
    correct: "Upanishads",
    distractors: ["Puranas", "Ramayana", "Arthashastra"],
    category: "texts",
  },
  {
    id: "symbol-trishula",
    topic: "Symbols",
    subject: "Trishula",
    fact: "The trishula is a trident strongly associated with Shiva.",
    correct: "Trishula",
    distractors: ["Sudarshana Chakra", "Vajra", "Gada"],
    category: "symbols",
  },
  {
    id: "symbol-chakra",
    topic: "Symbols",
    subject: "Sudarshana Chakra",
    fact: "The Sudarshana Chakra is a discus traditionally associated with Vishnu.",
    correct: "Sudarshana Chakra",
    distractors: ["Trishula", "Vajra", "Gada"],
    category: "symbols",
  },
  {
    id: "symbol-vajra",
    topic: "Symbols",
    subject: "Vajra",
    fact: "The vajra is a thunderbolt weapon strongly associated with Indra in Vedic and later traditions.",
    correct: "Vajra",
    distractors: ["Trishula", "Gada", "Sudarshana Chakra"],
    category: "symbols",
  },
  {
    id: "symbol-gada",
    topic: "Symbols",
    subject: "Gada",
    fact: "A gada, or mace, is a traditional weapon associated with figures such as Vishnu and Hanuman.",
    correct: "Gada",
    distractors: ["Vajra", "Trishula", "Veena"],
    category: "symbols",
  },
  {
    id: "symbol-veena",
    topic: "Symbols",
    subject: "Veena",
    fact: "The veena is a musical instrument traditionally associated with Saraswati.",
    correct: "Veena",
    distractors: ["Flute", "Conch", "Trident"],
    category: "symbols",
  },
  {
    id: "symbol-shankha",
    topic: "Symbols",
    subject: "Shankha",
    fact: "The shankha, or conch, is an important symbol and ritual object associated especially with Vishnu.",
    correct: "Shankha",
    distractors: ["Veena", "Trishula", "Vajra"],
    category: "symbols",
  },
  {
    id: "symbol-lotus",
    topic: "Symbols",
    subject: "Lotus",
    fact: "The lotus is a prominent religious symbol in Hindu traditions and is associated with purity and spiritual unfolding.",
    correct: "Lotus",
    distractors: ["Peacock", "Conch", "Trident"],
    category: "symbols",
  },
  {
    id: "festival-diwali",
    topic: "Festivals",
    subject: "Diwali",
    fact: "Diwali is a major Hindu festival often associated with lights, renewal and the victory of light over darkness.",
    correct: "Diwali",
    distractors: ["Holi", "Navaratri", "Raksha Bandhan"],
    category: "festivals",
  },
  {
    id: "festival-holi",
    topic: "Festivals",
    subject: "Holi",
    fact: "Holi is widely known as the festival of colors.",
    correct: "Holi",
    distractors: ["Diwali", "Navaratri", "Janmashtami"],
    category: "festivals",
  },
  {
    id: "festival-janmashtami",
    topic: "Festivals",
    subject: "Janmashtami",
    fact: "Janmashtami celebrates the birth of Krishna.",
    correct: "Janmashtami",
    distractors: ["Rama Navami", "Diwali", "Holi"],
    category: "festivals",
  },
  {
    id: "festival-ramanavami",
    topic: "Festivals",
    subject: "Rama Navami",
    fact: "Rama Navami celebrates the birth of Rama.",
    correct: "Rama Navami",
    distractors: ["Janmashtami", "Diwali", "Maha Shivaratri"],
    category: "festivals",
  },
  {
    id: "festival-shivaratri",
    topic: "Festivals",
    subject: "Maha Shivaratri",
    fact: "Maha Shivaratri is a major festival dedicated to Shiva.",
    correct: "Maha Shivaratri",
    distractors: ["Janmashtami", "Rama Navami", "Holi"],
    category: "festivals",
  },
  {
    id: "festival-navaratri",
    topic: "Festivals",
    subject: "Navaratri",
    fact: "Navaratri is a festival period devoted in many traditions to the worship of the Goddess in her various forms.",
    correct: "Navaratri",
    distractors: ["Diwali", "Holi", "Janmashtami"],
    category: "festivals",
  },
  {
    id: "festival-rakshabandhan",
    topic: "Festivals",
    subject: "Raksha Bandhan",
    fact: "Raksha Bandhan is traditionally associated with the bond between siblings, especially sisters and brothers.",
    correct: "Raksha Bandhan",
    distractors: ["Navaratri", "Holi", "Diwali"],
    category: "festivals",
  },
];
